title: Damian Hernandez
logo: /assets/img/profile_field_cropped.jpg
description: |
  NSF PRFB Fellow | Plant-Microbial Ecologist | Data Scientist
  Building genes-to-ecosystems frameworks of how plants and microbes get along.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
twitter_username: damianmicroeco
github_username: damianmicroeco