title: Damian Hernandez
title_separator: "-"
logo: /assets/img/longer_profile_cut.png
description: |
  NSF PRFB Fellow | Plant-Microbial Ecologist | Data Scientist
  Building genes-to-ecosystems frameworks of how plants and microbes get along.
  University of Toronto and Vrije Universiteit Amsterdam
theme: jekyll-theme-minimal
email: damianhernandez.microeco@gmail.com
twitter: damianmicroeco
linkedin: damianmicroeco
github: damianmicroeco
googlescholar: https://scholar.google.com/citations?user=fqffm8YAAAAJ&hl=en&oi=ao